config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'login#index'
  get 'contacts' => 'contacts#new' 

  namespace :admin do
    get 'login' => 'sessions#new', :as => 'login'
  end

  namespace :admin do
    get 'logout' => 'sessions#destroy', :as => 'logout'
  end

  resources :posts, :categories, :contacts
  
  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources "contacts", only: [:new, :create]

  root 'posts#index'

  resources :posts do
  	resources :comments
  end

  get 'about' => 'about#index'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts

	validates :name, presence: true

	def self.search(query)
		where("name like ?","%#{query}%")
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category
	belongs_to :user
	has_many :comments
	
	validates :title, presence: true
	validates :category_id, presence: true
	validates :body, presence: true

	has_attached_file :image,  :default_url => ":style/rails1.jpg"
	validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 2.megabyte }
	def self.search(query)
		where("title like ? OR body like ?","%#{query}%","%#{query}%" )
	end
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :password
	before_save :encrypt_password

	has_many :posts

	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true
	validates :password, confirmation: true

	def self.authentication(email, password)
	    user = find_by_email(email)
	    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
	       user
	    else
	   	   nil
	    end
	end
	
	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)	   	
	   end
	end 
	def self.search(query)
		where("name like ? OR email like ?","%#{query}%","%#{query}%")
	end     
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@category = Category.find(params[:id])
  	@categories = Category.all
  	@posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.create(comments_params)

  	flash[:notice] = "Comment Added"
  end

  private
  def comments_params
  	params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  	redirect_to admin_login_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@categories = Category.all
    if params[:search]
        @posts = Post.search(params[:search]).all.order('created_at DESC')
     else
        @posts = Post.all.order('created_at DESC')
     end
  end

  def show
  	@post = Post.find(params[:id])
  	@categories = Category.all
  	@comment = Comment.new
  	@comments = Comment.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>#maket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <%= stylesheet_link_tag 'admin_application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
   <%= favicon_link_tag asset_path('favicon.ico') %>
</head>
<body>
<div class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <a class="navbar-brand" href="/"><h1>M#1Bac<span>/Manager</span></h1></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'admin/posts' ? 'active' : '' %>"><%= link_to "Posts", admin_posts_path %></li>
            <li class="<%= params[:controller] == 'admin/categories' ? 'active' : '' %>"><%= link_to "Categories", admin_categories_path %></li>
            <li class="<%= params[:controller] == 'admin/users' ? 'active' : '' %>"><%= link_to "Users", admin_users_path %></li>
          </ul>
         <%=render 'partials/admin/search'%>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="well">
              <div class="pull-right">
                <% if current_user %>
                Logged in as <%=current_user.email %>
                <%= link_to 'logout', admin_logout_path %>
                <% else %>
                <%= link_to "Log in", admin_login_path %>
                <% end %>
              </div>
              <!-- Alerts & Messages -->
              <% if flash[:notice] %>
                <div class="alert alert-success"><%= flash[:notice] %></div>
              <% end %>

              <% if flash[:alert] %>
                <div class="alert alert-danger"><%= flash[:alert] %></div>
              <% end %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </section>
   
    <footer>
      <p> 2020 | Copyright &copy; | <small> Product of Shakhan Abdiev</small></p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
</body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>#maket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <%= stylesheet_link_tag 'login', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   <%= favicon_link_tag asset_path('favicon.ico') %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/partials/_comments.html.erb
<div class="comments">
	<h2 class="page-header"><%= @post.comments.length == 0 ? 'No Comments' : "#{@post.comments.length}  Comments" %></h2>
	<% @post.comments.each do |comment| %>
	   <div class="comment">
	   	  <div class="row well">
	   		<div class="col-md-2 avatar_user">
	   			<%= image_tag('user.jpg') %>
	   		</div>
	   		<div class="col-md-10">
	   			<div class="well">
	   				<h4> <%comment.name %> <span>/ <%= comment.created_at.to_time.strftime('%B %e at %l:%M %p')%> </span> </h4>
	   				<%=comment.body %>
	   			</div>
	   		</div>
	   	  </div>
	   </div>
	<% end %>
	<div class="well add-comment">
		<h2 class="page-header"> Add Comment</h2>
		<%= form_for([@post, @post.comments.build]) do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, class:'form-control'%>
		</div>
		<div class="form-group">
			<%= f.label :email %>
			<%= f.text_field :email, class:'form-control'%>
		</div>
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, class:'form-control'%>
		</div>
		<div class="form-group">
			<%= f.submit "Submit", class:'btn btn-primary' %>
		</div>
		<%end%>
	</div>
</div>

app/views/partials/_footer.html.erb
<footer>
      <p>Copyright &copy; 2020 </p>
</footer>

app/views/partials/_search.html.erb
<%= form_tag(posts_path, :method => "get", id:"search-form", class:"search-form pull-right") do %>
    <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class:'form-control'%>
    </div>
          <%=submit_tag "Search", :name => nil, class:'btn btn-primary'%>
  <%end%>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'posts' or params[:controller] == 'categories'  %>
    <div class="list-group">
	<%@categories.each do |category| %>
	    <%=link_to	category.name, category_path(category.id), class:'list-group-item' %>
	 <%end%>
  </div>
<% end %>

app/views/partials/admin/_search.html.erb
<% if params[:controller] == 'admin/posts' %>
   <%= form_tag(admin_posts_path, :method => "get", id:"search-form", class:"search-form pull-right") do %>
    <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class:'form-control'%>
    </div>
          <%=submit_tag "Search", :name => nil, class:'btn btn-primary'%>
  <%end%>
<%elsif params[:controller] == 'admin/categories' %>
 <%= form_tag(admin_categories_path, :method => "get", id:"search-form", class:"search-form pull-right") do %>
    <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search Categories", class:'form-control'%>
    </div>
          <%=submit_tag "Search", :name => nil, class:'btn btn-primary'%>
  <%end%>
<%elsif   params[:controller] == 'admin/users' %>
 <%= form_tag(admin_users_path, :method => "get", id:"search-form", class:"search-form pull-right") do %>
    <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search Users", class:'form-control'%>
    </div>
          <%=submit_tag "Search", :name => nil, class:'btn btn-primary'%>
  <%end%>  
<%end%>  