config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'login#index'
  get 'contacts' => 'contacts#new' 

  namespace :admin do
    get 'login' => 'sessions#new', :as => 'login'
  end

  namespace :admin do
    get 'logout' => 'sessions#destroy', :as => 'logout'
  end

  resources :posts, :categories, :contacts
  
  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources "contacts", only: [:new, :create]

  root 'posts#index'

  resources :posts do
  	resources :comments
  end

  get 'about' => 'about#index'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts

	validates :name, presence: true

	def self.search(query)
		where("name like ?","%#{query}%")
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category
	belongs_to :user
	has_many :comments
	
	validates :title, presence: true
	validates :category_id, presence: true
	validates :body, presence: true

	has_attached_file :image,  :default_url => ":style/rails1.jpg"
	validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 2.megabyte }
	def self.search(query)
		where("title like ? OR body like ?","%#{query}%","%#{query}%" )
	end
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :password
	before_save :encrypt_password

	has_many :posts

	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true
	validates :password, confirmation: true

	def self.authentication(email, password)
	    user = find_by_email(email)
	    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
	       user
	    else
	   	   nil
	    end
	end
	
	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)	   	
	   end
	end 
	def self.search(query)
		where("name like ? OR email like ?","%#{query}%","%#{query}%")
	end     
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController <Admin::ApplicationController
  before_action :verify_logged_in
  def new
    @page_title = 'Add Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category Created'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = 'Category Updated'

      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    flash[:notice] = 'Category Removed'

      redirect_to admin_categories_path
  end

  def index
    if params[:search]
        @categories = Category.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
     else
        @categories = Category.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
     end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@category = Category.find(params[:id])
  	@categories = Category.all
  	@posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.create(comments_params)

  	flash[:notice] = "Comment Added"
  end

  private
  def comments_params
  	params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  	redirect_to admin_login_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@categories = Category.all
    if params[:search]
        @posts = Post.search(params[:search]).all.order('created_at DESC')
     else
        @posts = Post.all.order('created_at DESC')
     end
  end

  def show
  	@post = Post.find(params[:id])
  	@categories = Category.all
  	@comment = Comment.new
  	@comments = Comment.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/categories/create.html.erb
<h1>Admin::Categories#create</h1>
<p>Find me in app/views/admin/categories/create.html.erb</p>

app/views/admin/categories/destroy.html.erb
<h1>Admin::Categories#destroy</h1>
<p>Find me in app/views/admin/categories/destroy.html.erb</p>

app/views/admin/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for [:admin, @category] do |f| %>
	<!-- Check for errors -->
	<% if @category.errors.any? %>
	    <% @category.errors.full_messages.each do |msg| %>
	    	<!-- Show errors -->
	      	<div class="alert alert-danger"><%= msg %></div>
	    <% end %>
  	<% end %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name ,class:'form-control' %>
	</div>
	<br>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", admin_categories_path, class:'btn btn-default' %>
<% end %>

app/views/admin/categories/index.html.erb
<h2 class="page-header">Manage Categories <%= link_to "Create New", new_admin_category_path, class:'btn btn-success pull-right' %></h2>
<table class="table table-striped">
<tr>
  <th>Category Title</th>
  <th>Create Date</th>
  <th>Actions</th>
</tr>
<% @categories.each do |category| %>
	<tr>
	  <td><%= category.name %></td>  
	  <td><%= category.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>    
	  <td><%= link_to "Edit", edit_admin_category_path(category), class:'btn btn-primary' %> <%= link_to "Delete", admin_category_path(category), class:'btn btn-danger', method: :delete, data: {confirm: 'Are you sure'} %></td>
	</tr>
<% end %>
</table>
<%=will_paginate @categories%>

app/views/admin/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for [:admin, @category] do |f| %>
	<!-- Check for errors -->
	<% if @category.errors.any? %>
	    <% @category.errors.full_messages.each do |msg| %>
	    	<!-- Show errors -->
	      	<div class="alert alert-danger"><%= msg %></div>
	    <% end %>
  	<% end %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name ,class:'form-control' %>
	</div>
	<br>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", admin_categories_path, class:'btn btn-default' %>
<% end %>

app/views/admin/categories/show.html.erb
<h1>Admin::Categories#show</h1>
<p>Find me in app/views/admin/categories/show.html.erb</p>

app/views/admin/categories/update.html.erb
<h1>Admin::Categories#update</h1>
<p>Find me in app/views/admin/categories/update.html.erb</p>

app/views/categories/show.html.erb
<h2> <%= @category.name %> </h2>
<div id="post-index">
  <% if @posts.exists? %>
    <% @posts.each_slice(2) do |post| %>
       <div class="row">
       	<%post.each do |post| %>
         <div class="col-md-6">
        	<div class="post">
        		<%= image_tag post.image.url, width:'100%'%>
        		<div class="post-content">
        			<h3><%= post.title%></h3>
        			<small>Posted By <%= post.user.name %>  on <%= post.created_at.to_time.strftime('%B %e at %l:%M %p')%></small>
        			<%= raw post.body.truncate(140)%>
        			<%= link_to 'Read More', post_path(post), class:'btn btn-primary' %>
        	      </div>
               </div>
            </div>
         <%end%>
       </div>
     <%end%>
     <%else%>
     <p> No Post  yet</p>
    <%end%>
 </div>