config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'login#index'
  get 'contacts' => 'contacts#new' 

  namespace :admin do
    get 'login' => 'sessions#new', :as => 'login'
  end

  namespace :admin do
    get 'logout' => 'sessions#destroy', :as => 'logout'
  end

  resources :posts, :categories, :contacts
  
  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources "contacts", only: [:new, :create]

  root 'posts#index'

  resources :posts do
  	resources :comments
  end

  get 'about' => 'about#index'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts

	validates :name, presence: true

	def self.search(query)
		where("name like ?","%#{query}%")
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category
	belongs_to :user
	has_many :comments
	
	validates :title, presence: true
	validates :category_id, presence: true
	validates :body, presence: true

	has_attached_file :image,  :default_url => ":style/rails1.jpg"
	validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 2.megabyte }
	def self.search(query)
		where("title like ? OR body like ?","%#{query}%","%#{query}%" )
	end
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :password
	before_save :encrypt_password

	has_many :posts

	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true
	validates :password, confirmation: true

	def self.authentication(email, password)
	    user = find_by_email(email)
	    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
	       user
	    else
	   	   nil
	    end
	end
	
	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)	   	
	   end
	end 
	def self.search(query)
		where("name like ? OR email like ?","%#{query}%","%#{query}%")
	end     
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :verify_logged_in
  def new
    @page_title = 'Add User'
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User Created'
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = 'User Updated'

      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    flash[:notice] = 'User Removed'

      redirect_to admin_users_path
  end

  def index
    if params[:search]
        @users = User.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
     else
        @users = User.all.order('created_at DESC').paginate(:per_page => 6, :page => params[:page])
     end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@category = Category.find(params[:id])
  	@categories = Category.all
  	@posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.create(comments_params)

  	flash[:notice] = "Comment Added"
  end

  private
  def comments_params
  	params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  	redirect_to admin_login_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@categories = Category.all
    if params[:search]
        @posts = Post.search(params[:search]).all.order('created_at DESC')
     else
        @posts = Post.all.order('created_at DESC')
     end
  end

  def show
  	@post = Post.find(params[:id])
  	@categories = Category.all
  	@comment = Comment.new
  	@comments = Comment.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/users/create.html.erb
<h1>Admin::Users#create</h1>
<p>Find me in app/views/admin/users/create.html.erb</p>

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for [:admin, @user] do |f| %>
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |msg| %>
  <!---shows any error--->
      <div class="alert alert-danger"><%= msg %></div>
    <%end%>
  <%end%>
  <div class="form-group"> 
  	 <%= f.label :name  %><br>
  	 <%= f.text_field :name, class:'form-control'%><brl>
  </div>
  <div class="form-group"> 
  	 <%= f.label :email  %><br>
  	 <%= f.text_field :email, class:'form-control'%><brl>
  </div>
  <div class="form-group"> 
  	 <%= f.label :password  %><br>
  	 <%= f.password_field :password, class:'form-control'%><brl>
  </div>
  <div class="form-group"> 
  	 <%= f.label :password_confirmation  %><br>
  	 <%= f.password_field :password_confirmation, class:'form-control'%><brl>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary"%>
  <%= link_to "Cancel", admin_posts_path, class: "btn btn-default"%>
<%end%>

app/views/admin/users/index.html.erb
<h2 class="page-header">Manage User <%= link_to "Create New", new_admin_user_path, class:'btn btn-success pull-right' %></h2>
<% if @users.exists? %>
<table class="table table-striped">
<tr>
  <th>User Name</th>
  <th>User Email@</th>
  <th>Create Date</th>
  <th>Actions</th>
</tr>
<% @users.each do |user| %>
	<tr>
	  <td><%= user.name %></td>  
	  <td> <%= user.email %> </td>
	  <td><%= user.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>    
	  <td><%= link_to "Edit", edit_admin_user_path(user), class:'btn btn-primary' %> <%= link_to "Delete", admin_user_path(user), class:'btn btn-danger', method: :delete, data: {confirm: 'Are you sure'} %></td>
	</tr>
 <% end %>
</table>
<%=will_paginate @users%>
<%else%>
<p>There are no Users</p>
<%end%>

app/views/admin/users/new.html.erb
<h2><%=@page_title%></h2>

<%= form_for [:admin, @user] do |f| %>
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |msg| %>
  <!---shows any error--->
      <div class="alert alert-danger"><%= msg %></div>
    <%end%>
  <%end%>
  <div class="form-group"> 
  	 <%= f.label :name  %><br>
  	 <%= f.text_field :name, class:'form-control'%><brl>
  </div>
  <div class="form-group"> 
  	 <%= f.label :email  %><br>
  	 <%= f.text_field :email, class:'form-control'%><brl>
  </div>
  <div class="form-group"> 
  	 <%= f.label :password  %><br>
  	 <%= f.password_field :password, class:'form-control'%><brl>
  </div>
  <div class="form-group"> 
  	 <%= f.label :password_confirmation  %><br>
  	 <%= f.password_field :password_confirmation, class:'form-control'%><brl>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary"%>
  <%= link_to "Cancel", admin_posts_path, class: "btn btn-default"%>
<%end%>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>